[package]
name = "rari-tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
console = "0"
csv = "1"
dialoguer = "0"
rari-types = { path = "../rari-types" }
rari-utils = { path = "../rari-utils" }
rari-doc = { path = "../rari-doc" }
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tracing = "0.1"
concat-in-place = "1"

[dev-dependencies]
rari-types = { path = "../rari-types", features = ["testing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.12", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
  "gzip",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "gzip",
] }
