name: publish-npm

on:
  workflow_run:
    workflows: [build-and-upload-binaries]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'This would run npm publish.'
