on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-pr

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          skip-github-release: true
          repo-url: mdn/rari
          manifest-file: .release-please-manifest.json
